name: Build and Push to ghcr.io

on:
  release:
    types: [published]
  workflow_dispatch:
    

jobs:

  build_and_push:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker images for multiple architectures
      run: |
        # DOCKER_CLI_EXPERIMENTAL=enabled docker buildx create --use
        # DOCKER_CLI_EXPERIMENTAL=enabled docker buildx inspect --bootstrap
        
        docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository }}/traefik-forward-auth:amd64 -f Dockerfile --push .
        docker buildx build --platform linux/arm/v7 -t ghcr.io/${{ github.repository }}/traefik-forward-auth:arm -f Dockerfile.arm --push .
        docker buildx build --platform linux/arm64 -t ghcr.io/${{ github.repository }}/traefik-forward-auth:arm64 -f Dockerfile.arm64 --push .